version: '3'
services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "433:433"
    networks:
      - myNetwork
    depends_on:
      - mariadb
  mariadb:
    env_file: requirements/mariadb/.env
    build: ./requirements/mariadb/
    networks:
      - myNetwork
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
networks:
  myNetwork: {}
