version: '3'
services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    networks:
      - myNetwork
    volumes:
      - wp:/var/www/html
    restart: on-failure
    depends_on:
      - mariadb
    restart: on-failure
  mariadb:
    env_file: .env
    build: requirements/mariadb/
    container_name: mariadb
    image: mariadb
    networks:
      - myNetwork
    volumes:
      - mysql:/var/lib/mysql
    restart: on-failure
  wp:
    env_file: .env
    build: requirements/wordpress/
    container_name: wp
    image: wp
    networks:
      - myNetwork
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
    restart: on-failure

volumes:
   mysql:
    driver_opts:
      type: none
      device: "/home/alorain/data/mysql"
      o: bind
   wp:
    driver_opts:
      type: none
      device: "/home/alorain/data/wp"
      o: bind
networks:
  myNetwork: {}
