
UPDATE mysql.user SET Password=PASSWORD($ROOT_PASSWD) WHERE User='root';
DELETE FROM mysql.user WHERE user='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
DROP DATABASE test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';
CREATE DATABASE $DB_NAME DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE USER '$USER_NAME'@'localhost' IDENTIFIED BY '$USER_PASSWD';
GRANT ALL PRIVILEGES ON $DB_NAME. * TO '$USER_NAME'@'localhost';
FLUSH PRIVILEGES;
EXIT;
