FROM debian:buster

RUN apt update && apt install nginx -y && apt install openssl

COPY ./nginx.conf /etc/nginx/nginx.conf

RUN openssl req -new \
	 -newkey rsa:4096 \
	 -x509 -sha256 \
	 -days 365 -nodes \
	 -out /etc/nginx/ssl/MyCertificate.crti \
	 -keyout /etc/nginx/ssl/MyKey.key
CMD ["", ""]
