FROM debian:buster

RUN apt update && apt install nginx -y && apt install openssl

COPY ./nginx.conf /etc/nginx/conf.d/nginx.conf

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -new \
	 -newkey rsa:4096 \
	 -x509 -sha256 \
	 -days 365 -nodes \
	 -out /etc/nginx/ssl/MyCertificate.crt \
	 -keyout /etc/nginx/ssl/MyKey.key \
	 -subj '/CN=localhost'

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
